[package]
name = "cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
sprite_dicing = { path = "../lib", features = ["fs"] }
clap = { version = "4.5", features = ["derive"] }
clap_derive = "4.5"
