on:
  push:
  pull_request:

jobs:
  lint:
    name: lint editorconfig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: editorconfig
      run: |
          docker run --rm --volume=$PWD:/check mstruebing/editorconfig-checker
